using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Google.GenAI;
using Google.GenAI.Types;
using DocumentUtilities;
using Config;
using AutoExtraction;
using Infrastructure;

namespace DirectChatAiInteraction;

/// <summary>
/// [AI Context] A dedicated session for refining, formatting, and correcting raw LaTeX files.
/// Uses its own isolated API Key (API_KEY-latex-refinement) to separate quotas from extraction workloads.
/// [Human] Diese Klasse nimmt die rohen, gestückelten LaTeX-Teile und lässt die KI daraus ein perfektes, fließendes Gesamtdokument bauen.
/// </summary>
public class LatexRefinementSession {
  private readonly Client _client;
  private readonly LatexRefinementConfig _config;
  private readonly string? _singleFilePathToProcess; // New field for single-file processing

  // Constructor for GUI-driven batch processing (or general batch)
  public LatexRefinementSession(Client client, LatexRefinementConfig config) {
    _client = client;
    _config = config;
    _singleFilePathToProcess = null; // No single file specified
  }

  // Constructor for automated single-file processing (e.g., hand-off from auto-extraction)
  public LatexRefinementSession(Client client, LatexRefinementConfig config, string singleFilePathToProcess) {
    _client = client;
    _config = config;
    _singleFilePathToProcess = singleFilePathToProcess; // Specific file to process
  }

  /// <summary>
  /// [AI Context] Aggregates all fragmented .tex files generated by the AutoExtraction phase and submits them in a single batch to Gemini for structural and semantic merging.
  /// [Human] Startet den interaktiven Zusammenführungs-Prozess der erstellten .tex Dateien.
  /// </summary>
  public async Task StartAsync() {
    if (!_config.Enabled) {
      Console.WriteLine("\n[INFO] LaTeX Refinement ist in der Konfiguration deaktiviert. Überspringe die Ausführung.");
      return;
    }

    Console.WriteLine("\n==================================================");
    Console.WriteLine("   Starte LaTeX Refinement & Post-Processing");
    Console.WriteLine("==================================================");

    string[] files;
    string targetOutputFolder;
    string outputFileNameBase;

    if (_singleFilePathToProcess != null) {
      files = new[] { _singleFilePathToProcess };
      targetOutputFolder = Path.GetDirectoryName(_singleFilePathToProcess) ?? _config.TargetFolder; // Use source folder of the single file
      outputFileNameBase = Path.GetFileNameWithoutExtension(_singleFilePathToProcess).Replace("-offset", ""); // Remove -offset suffix
      Console.WriteLine($"\nVerarbeite einzelne Datei: {_singleFilePathToProcess}");
    }
    else {
      string sourceFolder = _config.SourceFolder;
      Console.WriteLine($"\nSuche nach .tex Dateien in: {sourceFolder}");
      if (!Directory.Exists(sourceFolder)) {
        Console.WriteLine("Ordner nicht gefunden. Bitte prüfe den SourceFolder in der Konfiguration.");
        return;
      }
      files = Directory.GetFiles(sourceFolder, "*.tex");
      targetOutputFolder = string.IsNullOrWhiteSpace(_config.TargetFolder) ? sourceFolder : _config.TargetFolder;
      outputFileNameBase = "refined_output";
    }

    if (files.Length == 0) {
      Console.WriteLine("Keine .tex Dateien im Ordner gefunden.");
      return;
    }

    // Prompt for confirmation only if not in single-file automatic mode
    if (_singleFilePathToProcess == null) {
      Console.WriteLine("\nFolgende Dateien wurden gefunden:");
      foreach (var file in files) {
        Console.WriteLine($"  - {Path.GetFileName(file)}");
      }

      Console.Write("\nMöchtest du diese Dateien an Gemini schicken und zusammenfügen lassen? (j/n): ");
      string? confirm = Console.ReadLine()?.Trim().ToLower();
      if (confirm != "j" && confirm != "y") {
        Console.WriteLine("Vorgang abgebrochen.");
        return;
      }
    }

    await _TexMergeAsync(files, targetOutputFolder, outputFileNameBase);
  }

  /// <summary>
  /// [AI Context] Orchestrates the merging of LaTeX parts using Gemini.
  /// This method encapsulates the logic for preparing the prompt, sending it to Gemini, and saving the merged output.
  /// </summary>
  /// <param name="files">The array of LaTeX part files to be merged.</param>
  /// <param name="targetOutputFolder">The folder where the merged file will be saved.</param>
  /// <param name="outputFileNameBase">The base name for the merged output file (e.g., "02-16-monday").</param>
  private async Task _TexMergeAsync(string[] files, string targetOutputFolder, string outputFileNameBase) {
    string geminiMdPath = _config.GeminiMdPath;
    string geminiMdContent = System.IO.File.Exists(geminiMdPath) ? await System.IO.File.ReadAllTextAsync(geminiMdPath) : "Keine System-Instruktion gefunden.";

    var parts = new List<Part>();
    parts.Add(new Part {
      Text = (_singleFilePathToProcess != null
              ? "Here is a pre-merged LaTeX document that was transcribed from a lecture video. It has already had its part overlaps removed and timestamps adjusted. " +
                "Your task is to review this document for any remaining structural or semantic inconsistencies, improve the LaTeX formatting where necessary, and ensure a smooth logical flow. " +
                "The goal is to produce a single, perfectly refined, and compilable LaTeX document suitable for a lecture script. " +
                "Maintain the existing spoken-clean and math-stroke environments. Do NOT perform any further merging. "
              : "Here are the generated lecture parts (in LaTeX format) that were transcribed from overlapping video segments.\n" +
                "CRITICAL: The original video segments were cut with a **3-minute overlap**. This means the end of one part and the beginning of the next part contain duplicate transcribed content.\n" +
                "Your primary task is to PERFECTLY MERGE these overlapping parts into a single, cohesive, and continuous document! Identify the overlapping regions, eliminate all duplicate sentences and equations, and stitch the narrative seamlessly together.\n" +
                "Ensure the final output is fully compilable, fix any structural LaTeX errors, and guarantee no overlapping artifacts remain.\n\n") +
             "=== SYSTEM INSTRUCTION USED FOR EXTRACTION ===\n" + geminiMdContent + "\n=== END SYSTEM INSTRUCTION ==="
    });

    foreach (var file in files) {
      string rawContent = await System.IO.File.ReadAllTextAsync(file);
      double partStartTimeSeconds = 0;

      // Try to extract PART_START_SECONDS from the first line
      var firstLineMatch = System.Text.RegularExpressions.Regex.Match(rawContent, @"% PART_START_SECONDS: (\d+(\.\d+)?)");
      if (firstLineMatch.Success && double.TryParse(firstLineMatch.Groups[1].Value, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out double parsedStartTime)) {
        partStartTimeSeconds = parsedStartTime;
        // Remove the comment line from the content before processing
        // Note: For single file mode, the file is already merged and offset. For batch mode, the timestamps are adjusted below.
        rawContent = LatexTimestampHelper.ExtractContentWithoutTimestampHeader(rawContent);
      }

      string content = (_singleFilePathToProcess != null) ? rawContent : LatexTimestampHelper.AdjustTimestamps(rawContent, partStartTimeSeconds);
      parts.Add(new Part { Text = $"\n\n=== PART: {Path.GetFileName(file)} ===\n{content}\n=== END OF PART ===" });
    }

    // [AI Context] Temperature is forced to 0.0f here. We want strictly deterministic merging and formatting, absolutely zero creative hallucination.
    // [Human] Temperatur strikt auf 0.0 gesetzt, damit die KI sich exakt an die Vorgaben hält und nicht anfängt, die Mathematik frei umzuschreiben.
    var requestConfig = new GenerateContentConfig {
      Temperature = 0.0f,
      MaxOutputTokens = 65535,
    };
    // ThinkingLevel is not supported by the current SDK's ThinkingConfig.
    // If this functionality is intended, please check for SDK updates or alternative configuration methods.
    if (_config.Model.Contains("gemini-2.5", StringComparison.OrdinalIgnoreCase)) {
      if (_config.ThinkingBudget.HasValue) {
        requestConfig.ThinkingConfig = new ThinkingConfig { ThinkingBudget = _config.ThinkingBudget };
      }
    }

    var history = new List<Content> { new Content { Role = "user", Parts = parts } };
    Console.WriteLine($"\nSende Refinement-Anfrage an Gemini ({_config.Model})...");

    await _ProcessRefinementRequestAsync(history, requestConfig, targetOutputFolder, outputFileNameBase);
  }

  /// <summary>
  /// [AI Context] Executes the Gemini API request for LaTeX refinement and handles saving the output.
  /// </summary>
  /// <param name="history">The chat history including the user's prompt with LaTeX parts.</param>
  /// <param name="requestConfig">The configuration for the content generation request.</param>
  /// <param name="targetOutputFolder">The folder where the merged file should be saved.</param>
  /// <param name="outputFileNameBase">The base name for the output merged file.</param>
  private async Task _ProcessRefinementRequestAsync(List<Content> history, GenerateContentConfig requestConfig, string targetOutputFolder, string outputFileNameBase) {
    string? fullText = await ApiResilience.ExecuteWithRetryAsync(
        apiCall: async () => {
          string responseText = "";
          var responseStream = _client.Models.GenerateContentStreamAsync(_config.Model, history, requestConfig);

          await foreach (var chunk in responseStream) {
            string text = chunk.Text ?? chunk.Candidates?[0]?.Content?.Parts?[0]?.Text ?? "";
            Console.Write(text);
            responseText += text;
          }
          return responseText;
        },
        maxRetries: 5,
        retryContext: "LaTeX Refinement"
    );

    if (!string.IsNullOrEmpty(fullText)) {
      if (!Directory.Exists(targetOutputFolder)) Directory.CreateDirectory(targetOutputFolder);

      string outPath = Path.Combine(targetOutputFolder, $"{outputFileNameBase}-merged.tex");
      await System.IO.File.WriteAllTextAsync(outPath, fullText);
      Console.WriteLine($"\n\n[Erfolg] Refined LaTeX erfolgreich gespeichert unter: {outPath}");

      var latexToolkit = new LatexToolkit();
      var (compileSuccess, compileLog) = await latexToolkit.CompilePdfAsync(outPath);
      if (!compileSuccess) {
        Console.WriteLine("\n[Fehler] PDF-Kompilierung fehlgeschlagen. Hier ist der Log:");
        Console.WriteLine("==================================================");
        Console.WriteLine(compileLog);
        Console.WriteLine("==================================================");
      }
    }
    else {
      Console.WriteLine($"\n[Fehler] Beim Refinement ist ein Fehler aufgetreten oder der Vorgang wurde abgebrochen.");
    }
  }

}