using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Google.GenAI;
using Google.GenAI.Types;
using DocumentUtilities;
using Config;
using AutoExtraction;
using Infrastructure;

namespace DirectChatAiInteraction;

/// <summary>
/// [AI Context] A dedicated session for refining, formatting, and correcting raw LaTeX files.
/// Uses its own isolated API Key (API_KEY-latex-refinement) to separate quotas from extraction workloads.
/// [Human] Diese Klasse nimmt die rohen, gestückelten LaTeX-Teile und lässt die KI daraus ein perfektes, fließendes Gesamtdokument bauen.
/// </summary>
public class LatexRefinementSession {
  private readonly Client _client;
  private readonly LatexRefinementConfig _config;

  public LatexRefinementSession(Client client, LatexRefinementConfig config) {
    _client = client;
    _config = config;
  }

  /// <summary>
  /// [AI Context] Aggregates all fragmented .tex files generated by the AutoExtraction phase and submits them in a single batch to Gemini for structural and semantic merging.
  /// [Human] Startet den interaktiven Zusammenführungs-Prozess der erstellten .tex Dateien.
  /// </summary>
  public async Task StartAsync() {
    Console.WriteLine("\n==================================================");
    Console.WriteLine("   Starte LaTeX Refinement & Post-Processing");
    Console.WriteLine("==================================================");

    string sourceFolder = _config.SourceFolder;
    Console.WriteLine($"\nSuche nach .tex Dateien in: {sourceFolder}");

    if (!Directory.Exists(sourceFolder)) {
      Console.WriteLine("Ordner nicht gefunden. Bitte prüfe den SourceFolder in der Konfiguration.");
      return;
    }

    var files = Directory.GetFiles(sourceFolder, "*.tex");
    if (files.Length == 0) {
      Console.WriteLine("Keine .tex Dateien im Ordner gefunden.");
      return;
    }

    Console.WriteLine("\nFolgende Dateien wurden gefunden:");
    foreach (var file in files) {
      Console.WriteLine($"  - {Path.GetFileName(file)}");
    }

    Console.Write("\nMöchtest du diese Dateien an Gemini schicken und zusammenfügen lassen? (j/n): ");
    string? confirm = Console.ReadLine()?.Trim().ToLower();
    if (confirm != "j" && confirm != "y") {
      Console.WriteLine("Vorgang abgebrochen.");
      return;
    }

    string geminiMdPath = _config.GeminiMdPath;
    string geminiMdContent = System.IO.File.Exists(geminiMdPath) ? await System.IO.File.ReadAllTextAsync(geminiMdPath) : "Keine System-Instruktion gefunden.";

    var parts = new List<Part>();
    parts.Add(new Part {
      Text = "Here are the generated lecture parts (in LaTeX format) that were transcribed from overlapping video segments.\n" +
             "CRITICAL: The original video segments were cut with a **3-minute overlap**. This means the end of one part and the beginning of the next part contain duplicate transcribed content.\n" +
             "Your primary task is to PERFECTLY MERGE these overlapping parts into a single, cohesive, and continuous document! Identify the overlapping regions, eliminate all duplicate sentences and equations, and stitch the narrative seamlessly together.\n" +
             "Ensure the final output is fully compilable, fix any structural LaTeX errors, and guarantee no overlapping artifacts remain.\n\n" +
             "=== SYSTEM INSTRUCTION USED FOR EXTRACTION ===\n" + geminiMdContent + "\n=== END SYSTEM INSTRUCTION ==="
    });

    foreach (var file in files) {
      string content = await System.IO.File.ReadAllTextAsync(file);
      parts.Add(new Part { Text = $"\n\n=== PART: {Path.GetFileName(file)} ===\n{content}\n=== END OF PART ===" });
    }

    var history = new List<Content> { new Content { Role = "user", Parts = parts } };

    // [AI Context] Temperature is forced to 0.0f here. We want strictly deterministic merging and formatting, absolutely zero creative hallucination.
    // [Human] Temperatur strikt auf 0.0 gesetzt, damit die KI sich exakt an die Vorgaben hält und nicht anfängt, die Mathematik frei umzuschreiben.
    var requestConfig = new GenerateContentConfig {
      Temperature = 0.0f,
      MaxOutputTokens = 65535,
    };

    if (_config.Model.Contains("gemini-3", StringComparison.OrdinalIgnoreCase)) {
      if (!string.IsNullOrWhiteSpace(_config.ThinkingLevel)) {
        requestConfig.ThinkingConfig = new ThinkingConfig { ThinkingLevel = _config.ThinkingLevel };
      }
    }
    else if (_config.Model.Contains("gemini-2.5", StringComparison.OrdinalIgnoreCase)) {
      if (_config.ThinkingBudget.HasValue) {
        requestConfig.ThinkingConfig = new ThinkingConfig { ThinkingBudget = _config.ThinkingBudget };
      }
    }

    Console.WriteLine($"\nSende Refinement-Anfrage an Gemini ({_config.Model})...");

    string? fullText = await ApiResilience.ExecuteWithRetryAsync(async () => {
      string responseText = "";
      var responseStream = _client.Models.GenerateContentStreamAsync(_config.Model, history, requestConfig);

      await foreach (var chunk in responseStream) {
        string text = chunk.Text ?? chunk.Candidates?[0]?.Content?.Parts?[0]?.Text ?? "";
        Console.Write(text);
        responseText += text;
      }
      return responseText;
    }, maxRetries: 5);

    if (!string.IsNullOrEmpty(fullText)) {
      string targetFolder = string.IsNullOrWhiteSpace(_config.TargetFolder) ? sourceFolder : _config.TargetFolder;
      if (!Directory.Exists(targetFolder)) {
        Directory.CreateDirectory(targetFolder);
      }

      string outPath = Path.Combine(targetFolder, "refined_output.tex");
      await System.IO.File.WriteAllTextAsync(outPath, fullText);
      Console.WriteLine($"\n\n[Erfolg] Refined LaTeX erfolgreich gespeichert unter: {outPath}");

      var latexToolkit = new LatexToolkit();
      await latexToolkit.CompilePdfAsync(outPath);
    }
    else {
      Console.WriteLine($"\n[Fehler] Beim Refinement ist ein Fehler aufgetreten oder der Vorgang wurde abgebrochen.");
    }
  }

}