using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Google.GenAI;
using Google.GenAI.Types;
using DocumentUtilities;

namespace AiInteraction;

// [AI Context] Configuration specifically for the post-processing phase. TargetFolder specifies where the compiled, polished .tex/.pdf will be dropped.
public class LatexRefinementConfig {
  public string GeminiMdPath { get; set; } = @"C:\Users\miche\latex\directors-cut-analysis2\gemini.md";
  public string Model { get; set; } = "gemini-2.5-pro";
  public string TargetFolder { get; set; } = @"D:\lecture-videos\analysis2\destination\tex-refinement\refined";
  public string SourceFolder { get; set; } = @"D:\lecture-videos\analysis2\destination\tex-refinement";
}

/// <summary>
/// [AI Context] A dedicated session for refining, formatting, and correcting raw LaTeX files.
/// Uses its own isolated API Key (API_KEY-latex-refinement) to separate quotas from extraction workloads.
/// [Human] Diese Klasse nimmt die rohen, gestückelten LaTeX-Teile und lässt die KI daraus ein perfektes, fließendes Gesamtdokument bauen.
/// </summary>
public class LatexRefinementSession {
  private readonly Client _client;
  private readonly LatexRefinementConfig _config;

  public LatexRefinementSession(Client client, LatexRefinementConfig config) {
    _client = client;
    _config = config;
  }

  /// <summary>
  /// [AI Context] Aggregates all fragmented .tex files generated by the AutoExtraction phase and submits them in a single batch to Gemini for structural and semantic merging.
  /// [Human] Startet den interaktiven Zusammenführungs-Prozess der erstellten .tex Dateien.
  /// </summary>
  public async Task StartAsync() {
    Console.WriteLine("\n==================================================");
    Console.WriteLine("   Starte LaTeX Refinement & Post-Processing");
    Console.WriteLine("==================================================");

    string sourceFolder = _config.SourceFolder;
    Console.WriteLine($"\nSuche nach .tex Dateien in: {sourceFolder}");

    if (!Directory.Exists(sourceFolder)) {
      Console.WriteLine("Ordner nicht gefunden. Bitte prüfe den SourceFolder in der Konfiguration.");
      return;
    }

    var files = Directory.GetFiles(sourceFolder, "*.tex");
    if (files.Length == 0) {
      Console.WriteLine("Keine .tex Dateien im Ordner gefunden.");
      return;
    }

    Console.WriteLine("\nFolgende Dateien wurden gefunden:");
    foreach (var file in files) {
      Console.WriteLine($"  - {Path.GetFileName(file)}");
    }

    Console.Write("\nMöchtest du diese Dateien an Gemini schicken und zusammenfügen lassen? (j/n): ");
    string? confirm = Console.ReadLine()?.Trim().ToLower();
    if (confirm != "j" && confirm != "y") {
      Console.WriteLine("Vorgang abgebrochen.");
      return;
    }

    string geminiMdPath = _config.GeminiMdPath;
    string geminiMdContent = System.IO.File.Exists(geminiMdPath) ? await System.IO.File.ReadAllTextAsync(geminiMdPath) : "Keine System-Instruktion gefunden.";

    var parts = new List<Part>();
    parts.Add(new Part {
      Text = "Here are the generated lecture parts (in LaTeX format) that were transcribed from overlapping video segments.\n" +
             "CRITICAL: The original video segments were cut with a **3-minute overlap**. This means the end of one part and the beginning of the next part contain duplicate transcribed content.\n" +
             "Your primary task is to PERFECTLY MERGE these overlapping parts into a single, cohesive, and continuous document! Identify the overlapping regions, eliminate all duplicate sentences and equations, and stitch the narrative seamlessly together.\n" +
             "Ensure the final output is fully compilable, fix any structural LaTeX errors, and guarantee no overlapping artifacts remain.\n\n" +
             "=== SYSTEM INSTRUCTION USED FOR EXTRACTION ===\n" + geminiMdContent + "\n=== END SYSTEM INSTRUCTION ==="
    });

    foreach (var file in files) {
      string content = await System.IO.File.ReadAllTextAsync(file);
      parts.Add(new Part { Text = $"\n\n--- TEIL: {Path.GetFileName(file)} ---\n{content}\n--- ENDE TEIL ---" });
    }

    var history = new List<Content> { new Content { Role = "user", Parts = parts } };

    // [AI Context] Temperature is forced to 0.0f here. We want strictly deterministic merging and formatting, absolutely zero creative hallucination.
    // [Human] Temperatur strikt auf 0.0 gesetzt, damit die KI sich exakt an die Vorgaben hält und nicht anfängt, die Mathematik frei umzuschreiben.
    var requestConfig = new GenerateContentConfig {
      Temperature = 0.0f,
      MaxOutputTokens = 65535,
      ThinkingConfig = new ThinkingConfig { ThinkingBudget = 4096 }
    };

    Console.WriteLine($"\nSende Refinement-Anfrage an Gemini ({_config.Model})...");
    int maxRetries = 5;
    int backoff = 30;

    for (int attempt = 1; attempt <= maxRetries; attempt++) {
      // [AI Context] Implements an exponential backoff retry mechanism specifically tuned for Google APIs handling massive payload sizes.
      try {
        if (attempt > 1) Console.WriteLine($"\n[API] Sende Anfrage (Versuch {attempt}/{maxRetries})...");
        var responseStream = _client.Models.GenerateContentStreamAsync(_config.Model, history, requestConfig);
        string fullText = "";

        await foreach (var chunk in responseStream) {
          string text = chunk.Text ?? chunk.Candidates?[0]?.Content?.Parts?[0]?.Text ?? "";
          Console.Write(text);
          fullText += text;
        }

        string targetFolder = string.IsNullOrWhiteSpace(_config.TargetFolder) ? sourceFolder : _config.TargetFolder;
        if (!Directory.Exists(targetFolder)) {
          Directory.CreateDirectory(targetFolder);
        }

        string outPath = Path.Combine(targetFolder, "refined_output.tex");
        await System.IO.File.WriteAllTextAsync(outPath, fullText);
        Console.WriteLine($"\n\n[Erfolg] Refined LaTeX erfolgreich gespeichert unter: {outPath}");

        // [AI Context] Triggers the local LatexToolkit to immediately verify the compilation integrity of the AI's output.
        // [Human] Automatische PDF Kompilierung im Hintergrund, um sofort zu testen, ob die KI valides LaTeX erzeugt hat.
        var latexToolkit = new LatexToolkit();
        await latexToolkit.CompilePdfAsync(outPath);
        break;
      }
      catch (Exception ex) {
        Console.WriteLine($"\n[Exception gefangen] Art der Exception: {ex.GetType().Name}");
        Console.WriteLine($"Originaler Fehlertext: {ex.Message}");

        bool isOverloaded = ex.Message.Contains("429") || ex.Message.Contains("503") || ex.Message.Contains("500") || ex.ToString().Contains("ServerError") || ex.Message.Contains("quota", StringComparison.OrdinalIgnoreCase) || ex.Message.Contains("high demand", StringComparison.OrdinalIgnoreCase) || ex.Message.Contains("Too Many Requests", StringComparison.OrdinalIgnoreCase);
        if (attempt < maxRetries && isOverloaded) {
          var retryMatch = System.Text.RegularExpressions.Regex.Match(ex.Message, @"""retryDelay""\s*:\s*""(\d+)s""");
          if (retryMatch.Success && int.TryParse(retryMatch.Groups[1].Value, out int serverSuggestedDelay)) {
            int waitTime = serverSuggestedDelay + 2;
            Console.WriteLine($"\n[Rate Limit] API schlägt Wartezeit vor. Warte {waitTime} Sekunden... (Versuch {attempt}/{maxRetries})");
            if (!await SmartDelayAsync(waitTime)) {
              Console.WriteLine("\n[INFO] Wartezeit durch Benutzer abgebrochen.");
              break; // Exit retry loop if user cancels
            }
          }
          else {
            Console.WriteLine($"\n[Rate Limit / Überlastung] Warte {backoff} Sekunden... (Versuch {attempt}/{maxRetries})");
            if (!await SmartDelayAsync(backoff)) {
              Console.WriteLine("\n[INFO] Wartezeit durch Benutzer abgebrochen.");
              break; // Exit retry loop if user cancels
            }
          }
          backoff *= 2; // Increment backoff for the next potential retry, regardless of whether server suggested a delay
        }
        else {
          Console.WriteLine($"\n[Fehler] Beim Refinement ist ein Fehler aufgetreten: {ex.Message}");
          break;
        }
      }
    }
  }

  /// <summary>
  /// Implements an interactive delay with user cancellation.
  /// Allows the user to interrupt long backoff periods by pressing any key.
  /// </summary>
  private async Task<bool> SmartDelayAsync(int seconds, string message = "Still waiting for the acknowledgment / processing...") {
    bool delayCanceled = false;
    ConsoleCancelEventHandler cancelHandler = (sender, e) => { e.Cancel = true; delayCanceled = true; };
    Console.CancelKeyPress += cancelHandler;
    try {
      int delaySteps = seconds * 10;
      for (int i = 0; i < delaySteps; i++) {
        if (delayCanceled) return false;
        await Task.Delay(100);
        if (!Console.IsInputRedirected && Console.KeyAvailable) {
          while (Console.KeyAvailable) Console.ReadKey(intercept: true);
          Console.WriteLine($"\n[System] {message}");
        }
      }
      return true;
    }
    finally {
      Console.CancelKeyPress -= cancelHandler;
    }
  }
}